name: Patches

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  apply-patches:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: clone
      run: |
        sudo apt-get update
        sudo apt-get install git
        git clone 'https://github.com/nsxiv/nsxiv.git'
    - name: apply-patches
      run: |
        for dir in "$PWD"/patches/*/; do
          find "$dir" \( -name '*.patch' -o -name '*.diff' \) -print |
          xargs -I{} -n 1 git log --format=format:'%ct {}%n' -- '{}' |
          sort -nr | head -n 1 | cut -d ' ' -f 2
        done | ( cd nsxiv && xargs -I{} /bin/sh -c 'if ! git apply --check {} 2>/dev/null; then echo "[FAILED]: $(basename {})"; fi' )

