name: Patches

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  apply-patches:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: clone
      run: |
        sudo apt-get update
        sudo apt-get install git
        git clone 'https://github.com/nsxiv/nsxiv.git'
    - name: apply-patches
      run: |
        cd nsxiv
        find "$PWD"/../patches -type f -name '*.patch' |
          xargs -I{} -n 1 git log --format=format:'%at {}%n' -- '{}' |
          sort -rn | {
            while read -r timestamp patchpath; do
              patchdir="${patchpath%/*}"
              patchdir="${patchdir##*/}"

              for applied in "$@"; do
                if [ "$patchdir" = "$applied" ]; then
                  continue 2
                fi
              done
              set -- "$@" "$patchdir"

              if ! git apply --check "$patchpath" 2>/dev/null; then
                echo "[FAILED]: $(basename "$patchpath")" >&2
                fail=1
              fi
            done
            exit "${fail:-0}"
          }
